services:
  gamevault-backend:
    build: .
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USERNAME: gamevault
      DB_PASSWORD: RANDOMPASSWORD
    ports:
      - 8080:8080
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamevault
      POSTGRES_PASSWORD: RANDOMPASSWORD
      POSTGRES_DB: gamevault
