version: "3.8"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: gamevault
      POSTGRES_PASSWORD: gamevault
      POSTGRES_DB: gamevault
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U pgweb -h 127.0.0.1
      interval: 5s
  pgweb:
    container_name: pgweb
    image: sosedoff/pgweb:latest
    environment:
      PGWEB_DATABASE_URL: postgres://gamevault:gamevault@db:5432/gamevault?sslmode=disable
    ports:
      - 8081:8081
    depends_on: 
      db:
        condition: service_healthy